name: Build & Publish Testerloop App Package 

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Login to GitHub Package Registry
        run: echo "//npm.pkg.github.com/:_authToken=${{secrets.NPM_TOKEN}}" >> ~/.npmrc
      - name: Checkout Repository with Submodules
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: ./scripts/install.sh
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
